name: CBP PR check

on:
  pull_request

jobs:
  build:
    name: Check PR
    runs-on: ubuntu-latest
    env:
      Resource_Group: zhp-cbp
    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Validate Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.Resource_Group }}
          template: ./infrastructure/cbp.bicep
          deploymentMode: Validate
      - name: TODOs
        run: |
          echo 'TODO: zbudować front (npm?)'
          echo 'TODO: zbudować backend (laravel)'
          echo 'TODO: puścić testy'

