name: CBP Prod deployment

on:
  push:
    branches: [production]

jobs:
  build:
    name: Build for prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: infrastructure-bicep
          path: infrastructure/cbp.bicep
          if-no-files-found: error

      - name: TODOs
        run: |
          echo 'TODO: zbudować front (npm?)'
          echo 'TODO: zbudować backend (laravel)'
          echo 'TODO: puścić testy'
          echo 'TODO: wystawić artefakt'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    env:
      Resource_Group: zhp-cbp
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/download-artifact@v3

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.Resource_Group }}
          template: ./infrastructure-bicep/cbp.bicep

      - name: TODOs
        run: |
          echo 'TODO: ściągnąć artefakty'
          echo 'TODO: nanieść migracje'
          echo 'TODO: wgrać aplikację'

