name: CBP PR check

on:
  push:
    branches: [pipelines-add]

jobs:
  build:
    name: Check PR
    runs-on: ubuntu-latest
    env:
      Resource_Group: zhp-cbp
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.Resource_Group }}
          template: ./infrastructure/cbp.bicep
          deploymentMode: Validate
          parameters: environment=prod
      
      - run: composer install
      - run: ./vendor/bin/pint
      - run: ./vendor/bin/pest --parallel        
      - run: echo 'php artisan migrate --database=testing'
      - run: echo 'php artisan db:seed --database=testing'
      - run: npm run build
          # echo 'TODO: zbudować front (npm?)'
          # echo 'TODO: zbudować backend (laravel)'
          # echo 'TODO: puścić testy'
          # echo 'composer install ; ./vendor/bin/pint'

